spring:
  application:
    name: tintero-social

  datasource:
    url: jdbc:h2:mem:db_books
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8082